### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by takuya-takeuchi** [takuya-takeuchi/DlibDotNet#1]
- [x] Remove delete void pointer
- [x] Point, DPoint, DRectangle and Rectangle converted to struct type
- [X] Compile on Linux
- [x] Change Pass-by-value to Pass-by-reference for copy object in native  #lib
- [x] Run on Linux
- [x] Run on Mac
- [ ] Support GIF (After mod CMakeLists.txt, giflib is not available)
- [ ] Clean Native source code

**Comment by FelikZ** [comment]
FYI: Currently it does not compile on OSX.

```bash
DLIB_PATH=/usr/local/Cellar/dlib/19.9/include/ GIFLIB_PATH=/usr/local/Cellar/giflib/5.1.4/ cmake -DCMAKE_CXX_FLAGS="-I/usr/local/Cellar/giflib/5.1.4/include" .
make
```

```
[ 20%] Building CXX object CMakeFiles/DlibDotNet.Native.dir/dlib/gui_core/gui_core_kernel_1.cpp.o
In file included from /Users/felikz/projects/.net/DlibDotNet/src/DlibDotNet.Native/dlib/gui_core/gui_core_kernel_1.cpp:1:
In file included from /Users/felikz/projects/.net/DlibDotNet/src/DlibDotNet.Native/dlib/gui_core/gui_core_kernel_1.h:6:
/usr/local/Cellar/dlib/19.9/include/dlib/gui_core/gui_core_kernel_1.h:19:10: error: 'windows.h' file not found with <angled> include; use "quotes" instead
#include <windows.h>
         ^~~~~~~~~~~
         "windows.h"
/usr/local/Cellar/dlib/19.9/include/dlib/gui_core/gui_core_kernel_1.h:20:10: fatal error: 'winuser.h' file not found
#include <winuser.h>
         ^~~~~~~~~~~
2 errors generated.
make[2]: *** [CMakeFiles/DlibDotNet.Native.dir/dlib/gui_core/gui_core_kernel_1.cpp.o] Error 1
make[1]: *** [CMakeFiles/DlibDotNet.Native.dir/all] Error 2
make: *** [all] Error 2
```

I was trying to disable building DLIB GUI part but apparently its not possible since your wrapper wraps this part too and does not respect `DLIB_NO_GUI_SUPPORT` flag.

**Comment by takuya-takeuchi** [comment]
Sorry for late reply.
You may find out, latest revision support gui module on Widows, MacOS and Linux.

**Comment by takuya-takeuchi** [comment]
For the time being close
